name: DeployFirstPractice
on: push
jobs:
  deploy:
  runs-on: ubuntu-latest
  steps:
    - name: Pull the code
      uses: actions/checkout@v3
    - name: Install node JS
      run: npm ci
    - name: Run Lint
      run: npm run lint
    - name: Run test
      run: npm run test